AllCops:
  TargetRubyVersion: 3.1

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
